--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem-pm-pl/Trident
build-by-default: true
branches:
- master
projects:
  Trident:
    path: ""
    icon: "/assets/trident.png"
    lint:
      phpstan: false
...
